"""The kernel's own classical-Nyaya validity check: a row this engine computed itself -- no third-party file
admitted by hash -- read back through `objective progress` on the `nyaya` track.

Unlike `nyaya.py`'s ask/audit path (agama, never reaching the ledger, because one LLM answer is testimony
rather than evidence), whether a syllogism is valid is DECIDABLE from the world it names: given a mapping from
locus to the properties holding there, whether the hetu pervades the sadhya is a set-theoretic fact, so
`derive_verdict` computes it rather than asking anything. The gold set it is scored against is asserted by
hand (from prabhasa-samskrutam's own worked examples, cross-checked in tests/test_nyaya_gold.py) rather than
generated by `derive_verdict` itself, so scoring it is not the derivation grading itself.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
from typer.testing import CliRunner

from pravrudhi.application import nyaya_validity as nv
from pravrudhi.application import objectives
from pravrudhi.cli.app import app
from pravrudhi_kernel.ledger import LedgerWriter

runner = CliRunner()

# prabhasa-nyaya main's own build (Score.lean, isSatpratipaksa and isBadhita all merged as of f47267f).
_LEAN_SCORE_BIN = Path("/home/ss/projects/prabhasa-nyaya/lean/.lake/build/bin/score")
requires_lean_scorer = pytest.mark.skipif(
    not _LEAN_SCORE_BIN.exists(), reason="prabhasa-nyaya's Lean `score` executable is not built at this path"
)


def test_derive_verdict_matches_the_five_hand_labelled_cases() -> None:
    # Cross-checked against prabhasa-samskrutam's own gate in tests/test_nyaya_gold.py; an independent
    # implementation disagreeing with either would mean one of them is wrong.
    for item in nv.GOLD:
        world = {locus: frozenset(props) for locus, props in item["world"].items()}
        assert nv.derive_verdict(world, item["paksa"], item["sadhya"], item["hetu"]) == item["expected"], item["id"]


def test_check_gold_set_reports_every_item_and_a_pooled_pass_rate() -> None:
    result = nv.check_gold_set()
    assert result["n"] == len(nv.GOLD)
    assert result["passed"] == result["n"]  # the shipped gold set is a set the derivation must pass
    assert set(result["items"]) == {item["id"] for item in nv.GOLD}


def test_record_writes_a_kernel_tier_row_on_the_nyaya_track(tmp_path: Path) -> None:
    (tmp_path / "research").mkdir()
    LedgerWriter.open(tmp_path / "research" / "ledger.jsonl", "0.1.0")

    row = nv.record(tmp_path, night=3, condition="base")

    assert row["track"] == "nyaya"
    assert row["tier"] == "kernel"  # the kernel computed this itself; no third-party file was admitted by hash
    assert row["tool"] == "pravrudhi-nyaya-validity"
    assert len(row["sha256"]) == 64
    assert row["metrics"]["nyaya_validity"]["pass_rate"] == 1.0
    assert row["condition"] == "base"


def test_record_writes_a_readable_result_file(tmp_path: Path) -> None:
    (tmp_path / "research").mkdir()
    LedgerWriter.open(tmp_path / "research" / "ledger.jsonl", "0.1.0")

    row = nv.record(tmp_path, night=0, condition="base")

    out = tmp_path / row["file"]
    assert out.exists()
    assert json.loads(out.read_text())["passed"] == row["n_samples"]["nyaya_validity"]


def test_objective_progress_reads_the_row_back_from_the_nyaya_track(tmp_path: Path) -> None:
    """The path the acceptance criterion names: evidence on the `nyaya` track from an executed run, read back
    through `objective progress` on the packaged prabhasa-nyaya objective."""
    (tmp_path / "research").mkdir()
    LedgerWriter.open(tmp_path / "research" / "ledger.jsonl", "0.1.0")
    nv.record(tmp_path, night=0, condition="base")

    obj = objectives.load(objectives.PACKAGED_OBJECTIVES / "prabhasa-nyaya.yaml")
    rows = objectives.progress(obj, tmp_path / "research" / "ledger.jsonl")
    row = next(r for r in rows if r.benchmark == "nyaya_validity pass_rate")

    assert row.state == "baseline_only"
    assert row.baseline is not None
    assert row.baseline.value == 1.0


def test_cli_validity_check_runs_the_kernel_check_and_reports_the_tier(tmp_path: Path) -> None:
    (tmp_path / "research").mkdir()
    LedgerWriter.open(tmp_path / "research" / "ledger.jsonl", "0.1.0")

    result = runner.invoke(app, ["nyaya", "validity-check", "--root", str(tmp_path)])

    assert result.exit_code == 0
    assert '"tier": "kernel"' in result.stdout
    assert '"track": "nyaya"' in result.stdout


@requires_lean_scorer
class TestTheConstructedGoldSet:
    """Session-3's A2 decisions, 2026-09-12: the six-bank constructed set, scored per class against
    prabhasa-nyaya's Lean verifier, additive to the 5-item smoke-check above."""

    def _env(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("PRABHASA_NYAYA_SCORE_BIN", str(_LEAN_SCORE_BIN))

    def test_record_constructed_reports_the_worst_decided_class_and_the_full_table(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        self._env(monkeypatch)
        (tmp_path / "research").mkdir()
        LedgerWriter.open(tmp_path / "research" / "ledger.jsonl", "0.1.0")

        row = nv.record_constructed(tmp_path, night=0, condition="base", per_class=15, seed=0)

        assert row["track"] == "nyaya"
        assert row["tier"] == "kernel"
        assert row["n_samples"]["nyaya_validity"] >= 15 * 6
        assert row["metrics"]["nyaya_validity"]["pass_rate"] == 1.0  # all six classes agree
        assert set(row["decided_classes"]) == {
            "valid", "asiddha", "viruddha", "savyabhicara", "satpratipaksa", "badhita",
        }
        assert row["not_decided_classes"] == []
        assert row["per_class"]["satpratipaksa"]["pass_rate"] == 1.0
        assert row["per_class"]["badhita"]["pass_rate"] == 1.0
        assert row["lean_source_commit"]

    def test_cli_constructed_flag_runs_the_per_class_check(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        self._env(monkeypatch)
        (tmp_path / "research").mkdir()
        LedgerWriter.open(tmp_path / "research" / "ledger.jsonl", "0.1.0")

        result = runner.invoke(
            app,
            ["nyaya", "validity-check", "--root", str(tmp_path), "--constructed", "--per-class", "10"],
            env={**os.environ, "PRABHASA_NYAYA_SCORE_BIN": str(_LEAN_SCORE_BIN)},
        )

        assert result.exit_code == 0, result.stdout
        assert '"tier": "kernel"' in result.stdout
