#!/usr/bin/env python3
"""Render CaseHOLD's held-out test split under a harness recipe, for the external proof tier.

Runs INSIDE `pravrudhi/ext-scorers`, because the prompt must be built by the same tokenizer and chat template
`docker/jobs/agent_choice.py` uses. A prompt rendered any other way would certify a harness that never ran:
`enable_thinking` alone changes how much of the budget the model spends before it answers, and that budget is
the knob this tier exists to certify.

What it emits:
  * `<cache>/casehold/test.parquet` -- one row per item with the FULLY RENDERED prompt and the gold letter.
  * `<tasks>/casehold_harness.yaml` -- an lm-eval `generate_until` task whose generation_kwargs come from the
    recipe, so the budget and decoding travel with it rather than being retyped.

What it CANNOT carry, stated here because a proof tier that quietly drops part of the harness is worse than
no proof tier:
  * `retries`. The harness re-asks when a reply commits to no letter; lm-eval has no equivalent. An unparsed
    reply is scored wrong here, so the external number is a LOWER BOUND on the harness -- conservative, which
    is the safe direction for a claim.
  * `n_samples` > 1. Self-consistency is a majority vote over whole replies; lm-eval's `repeats` plus a
    majority filter is a different aggregation. Refused rather than approximated.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

CASEHOLD_HOLDINGS = 5
LETTERS = "ABCDEFGHIJ"
# Positional, because the published header names its columns "0".."11" with no meaning attached. Mirrors
# `pravrudhi.application.corpus`, which is not importable here -- the kernel is not installed in this image.
_ID, _PROMPT, _FIRST_HOLDING, _LABEL = 0, 1, 2, 12
INSTRUCTION = (
    "The passage below cites a case whose holding has been masked as (<HOLDING>). "
    "Which of the following is the masked holding?"
)


def render_question(stem: str, holdings: list[str]) -> str:
    lines = [stem, ""]
    lines += [f"{LETTERS[i]}. {h.strip()}" for i, h in enumerate(holdings)]
    return "\n".join(lines)


def rows(source: Path) -> list[dict[str, str]]:
    csv.field_size_limit(sys.maxsize)  # a citing prompt is longer than the default field cap
    out: list[dict[str, str]] = []
    with source.open(newline="") as fh:
        reader = csv.reader(fh)
        next(reader, None)
        for record in reader:
            if len(record) <= _LABEL:
                continue
            label = str(record[_LABEL]).strip()
            if not label.isdigit() or not 0 <= int(label) < CASEHOLD_HOLDINGS:
                continue  # a gold with no option is dropped rather than mapped to some letter
            holdings = record[_FIRST_HOLDING : _FIRST_HOLDING + CASEHOLD_HOLDINGS]
            out.append(
                {
                    "id": str(record[_ID]),
                    "question": render_question(f"{INSTRUCTION}\n\n{record[_PROMPT].strip()}", holdings),
                    "answer": LETTERS[int(label)],
                }
            )
    return out


TASK_YAML = """\
# GENERATED by scripts/build_casehold_ext.py from a harness recipe. Do not hand-edit: the generation kwargs
# below must equal the recipe's, and a hand-edit is how one fact acquires two representations that disagree.
#
# Recipe: {recipe_path}
# Recipe sha256 (harness_json, the fields that execute): {recipe_sha}
# Split: CaseHOLD `test` -- never in the loop. The internal pool is `casehold-val`; the model track trains on
# `casehold-train`. This is CaseHOLD's own split boundary, not a filter applied here.
task: casehold_harness
dataset_path: parquet
dataset_kwargs:
  data_files:
    test: /cache/casehold/test.parquet
test_split: test
output_type: generate_until
# The prompt is pre-rendered through the model's own chat template, exactly as agent_choice.py builds it, so
# lm-eval performs plain completion on the identical string the harness would have sent.
doc_to_text: "{{{{query}}}}"
doc_to_target: "{{{{answer}}}}"
generation_kwargs:
  max_gen_toks: {max_new_tokens}
  do_sample: {do_sample}
  temperature: {temperature}
  top_p: 0.95
  until: []
process_results: !function casehold_utils.process_results
metric_list:
  # Read `unparsed` FIRST. A completion that never states a letter scores zero on exact_match exactly as a
  # wrong letter does, so without this a harness that ran out of generation budget is indistinguishable from
  # one that reasoned badly. That is the failure that made the law baseline read 0.1042.
  - metric: unparsed
    aggregation: mean
    higher_is_better: false
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--harness", type=Path, required=True)
    ap.add_argument("--csv", type=Path, required=True)
    ap.add_argument("--model-dir", required=True)
    ap.add_argument("--cache", type=Path, default=Path("/cache"))
    ap.add_argument("--tasks", type=Path, default=Path("/tasks"))
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    import hashlib

    import pandas as pd
    from transformers import AutoTokenizer

    h = json.loads(args.harness.read_text())
    if int(h.get("n_samples", 1)) > 1:
        raise SystemExit(
            f"REFUSED: recipe sets n_samples={h['n_samples']}. Self-consistency is a majority vote over whole "
            f"replies and lm-eval's `repeats` is a different aggregation; approximating it would certify a "
            f"harness that never ran."
        )
    executes = {k: v for k, v in h.items() if k not in ("rationale", "strategy", "execution_family")}
    recipe_sha = hashlib.sha256(json.dumps(executes, sort_keys=True).encode()).hexdigest()

    tok = AutoTokenizer.from_pretrained(args.model_dir)
    items = rows(args.csv)
    if args.limit:
        items = items[: args.limit]

    records = []
    for item in items:
        user = str(h["template"]).replace("{question}", item["question"])
        msgs = [{"role": "system", "content": h["system_prompt"]}, {"role": "user", "content": user}]
        query = tok.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=True, enable_thinking=bool(h.get("thinking", False))
        )
        records.append({"id": item["id"], "query": str(query), "answer": item["answer"]})

    out = args.cache / "casehold"
    out.mkdir(parents=True, exist_ok=True)
    pd.DataFrame.from_records(records).to_parquet(out / "test.parquet", index=False)

    temperature = float(h.get("temperature", 0.2))
    args.tasks.mkdir(parents=True, exist_ok=True)
    (args.tasks / "casehold_harness.yaml").write_text(
        TASK_YAML.format(
            recipe_path=str(args.harness),
            recipe_sha=recipe_sha,
            max_new_tokens=int(h.get("max_new_tokens", 512)),
            do_sample=str(temperature > 0).lower(),
            temperature=max(temperature, 1e-5),
        )
    )
    carried = ["system_prompt", "template", "max_new_tokens", "temperature", "thinking"]
    dropped = [k for k in ("retries",) if int(h.get(k, 0) or 0) > 0]
    print(json.dumps({"items": len(records), "recipe_sha256": recipe_sha, "carried": carried, "dropped": dropped}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
