"""The kernel's own classical-Nyaya validity check: an evidence row this engine computed itself, not a
third-party file admitted by hash.

This is deliberately not `nyaya.py`'s ask/audit path, which never reaches the ledger because one LLM's answer
is agama (testimony), not evidence. Whether a syllogism is valid is instead DECIDABLE from the world it names:
given a mapping from locus to the properties holding there, whether the hetu pervades the sadhya is a
set-theoretic fact, so `derive_verdict` computes it rather than asking anything -- the same reasoning
`scripts/nyaya_gold.py` gives for admitting a constructed gold set as evidence at all.

The gold set below is asserted BY HAND, from prabhasa-samskrutam's own worked examples (also cross-checked in
tests/test_nyaya_gold.py), rather than generated by `derive_verdict`: a gold set whose labels come from the
function being scored would grade the checker with itself. `scripts/nyaya_gold.py`'s larger, generated set is
deliberately not imported here for the same reason -- a bug shared by both would not cancel out.

`record` admits the result to the ledger with tier `kernel` (`pravrudhi.application.external.TIER_KERNEL`),
not `external`: the kernel ran this check in this process, right now, so there is no third party's file to
hash for provenance. A result file is still written and hashed, so the row stays reproducible the same way an
external one is.

`record_constructed` (2026-09-12, session-3's A2/A4 decisions) is additive: the 5-item smoke-check above is
unaffected. It runs `nyaya_gold.build_gold_set`'s six-bank constructed set through `nyaya_gold_score`, which
scores every class -- `Verdict.of` for four, `isSatpratipaksa` and `isBadhita` (A4) for the other two --
against prabhasa-nyaya's Lean deciders, never this repo's own generator or derivation -- so `nyaya_validity
pass_rate` gets a real n (hundreds per class, not 2 and 3) the first time something actually calls it with
`--constructed`.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from pravrudhi.application.external import TIER_KERNEL, TOOL_NYAYA_VALIDITY
from pravrudhi.application.nyaya_gold import build_gold_set
from pravrudhi.application.nyaya_gold_score import score_bin_path, score_gold_set
from pravrudhi_kernel.ledger import LedgerWriter

TRACK = "nyaya"
#: The metric name exactly as `headlines()` forms it, so an objective's `metric:` line and this row cannot
#: disagree about which number they mean.
METRIC = "nyaya_validity pass_rate"

World = dict[str, frozenset[str]]

#: Hand-labelled by prabhasa-samskrutam's own gate (scripts/m4/m4_gate_frt_nyaya.py), asserted independently of
#: `derive_verdict` below so scoring the derivation against them is not the derivation grading itself.
GOLD: tuple[dict[str, Any], ...] = (
    {
        "id": "pervasion-corroborated", "paksa": "mountain", "sadhya": "fire", "hetu": "smoke", "expected": "valid",
        "world": {"mountain": ("smoke", "fire"), "kitchen": ("smoke", "fire"), "iron-ball": ("fire",), "lake": ("water",)},
    },
    {
        "id": "self-pervasion", "paksa": "mountain", "sadhya": "smoke", "hetu": "smoke", "expected": "valid",
        "world": {"mountain": ("smoke", "fire"), "kitchen": ("smoke", "fire"), "iron-ball": ("fire",), "lake": ("water",)},
    },
    {
        "id": "hetu-absent-from-paksa", "paksa": "lake", "sadhya": "fire", "hetu": "smoke", "expected": "asiddha",
        "world": {"mountain": ("smoke", "fire"), "kitchen": ("smoke", "fire"), "iron-ball": ("fire",), "lake": ("water",)},
    },
    {
        "id": "hetu-strays-at-one-locus", "paksa": "mountain", "sadhya": "smoke", "hetu": "fire", "expected": "savyabhicara",
        "world": {"mountain": ("smoke", "fire"), "kitchen": ("smoke", "fire"), "iron-ball": ("fire",), "lake": ("water",)},
    },
    {
        "id": "hetu-never-accompanies-sadhya", "paksa": "mountain", "sadhya": "water", "hetu": "fire", "expected": "viruddha",
        "world": {"mountain": ("smoke", "fire"), "kitchen": ("smoke", "fire"), "iron-ball": ("fire",), "lake": ("water",)},
    },
)


def derive_verdict(world: World, paksa: str, sadhya: str, hetu: str) -> str:
    """The classical verdict for one inference in one world, derived from set relations alone -- no model, no
    network. Order is load-bearing: a reason not established in the subject is asiddha whatever else is true
    elsewhere, and universal deviation is viruddha rather than savyabhicara. See scripts/nyaya_gold.py for the
    fuller account these same rules follow."""
    if paksa not in world or hetu not in world[paksa]:
        return "asiddha"
    hetu_loci = [locus for locus, props in world.items() if hetu in props]
    deviating = [locus for locus in hetu_loci if sadhya not in world[locus]]
    if deviating:
        return "viruddha" if len(deviating) == len(hetu_loci) else "savyabhicara"
    corroborating = [locus for locus in hetu_loci if locus != paksa]
    return "valid" if corroborating else "aprasiddha"


def check_gold_set(gold: tuple[dict[str, Any], ...] = GOLD) -> dict[str, Any]:
    """Score `derive_verdict` against the hand-labelled gold set. Per-item pass/fail travels with the pooled
    rate, so a later run can be paired against this one the same way harness pass@1 rows are."""
    items: dict[str, int] = {}
    for item in gold:
        world = {locus: frozenset(props) for locus, props in item["world"].items()}
        got = derive_verdict(world, item["paksa"], item["sadhya"], item["hetu"])
        items[item["id"]] = int(got == item["expected"])
    return {"n": len(items), "passed": sum(items.values()), "items": items}


def record(root: Path, night: int = 0, condition: str = "base") -> dict[str, Any]:
    """Run the check and admit it to the ledger under track `nyaya`, tier `kernel`.

    Unlike `external.record_external`, there is no third-party file to admit: this process computed `result`
    itself, just now. A result file is still written under `research/nyaya/validity/` and hashed, so the row
    is reproducible the same way an externally-scored one is -- only the tier says who ran the check.
    """
    root = Path(root)
    result = check_gold_set()
    out_dir = root / "research" / "nyaya" / "validity"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"night-{night}-{condition.replace(':', '-')}.json"
    out_path.write_text(json.dumps(result, indent=1, sort_keys=True) + "\n")
    sha256 = hashlib.sha256(out_path.read_bytes()).hexdigest()

    n, k = result["n"], result["passed"]
    payload = {
        "kind": "external_eval",
        "severity": "info",
        "tier": TIER_KERNEL,
        "track": TRACK,
        "condition": condition,
        "model": "pravrudhi-kernel",
        "file": str(out_path.relative_to(root)),
        "sha256": sha256,
        "tool": TOOL_NYAYA_VALIDITY,
        "n_samples": {"nyaya_validity": n},
        "metrics": {"nyaya_validity": {"pass_rate": k / n if n else 0.0}},
        "items": result["items"],
    }
    ledger = root / "research" / "ledger.jsonl"
    w = LedgerWriter.open(ledger, "0.1.0")
    ev = w.append("audit", "auditor", payload, epoch=0, night=night)
    return {"seq": ev.seq, **payload}


def record_constructed(
    root: Path, night: int = 0, condition: str = "base", per_class: int = 100, seed: int = 0,
) -> dict[str, Any]:
    """Run the six-bank constructed gold set through prabhasa-nyaya's Lean deciders and admit the per-class
    result to the ledger, same track and metric name as `record` above.

    As of 2026-09-12 (session-3's A4) all six classes are decided -- `Verdict.of` for four, `isSatpratipaksa`
    and `isBadhita` for the other two. `nyaya_validity pass_rate` is the worst decided class's pass rate (a
    genuine min over six now, not four), never a pooled average, so one easy class filling up cannot hide a
    hard one still broken. The row also records `lean_source_commit`: which prabhasa-nyaya commit the
    `score` binary that produced these numbers was built from.
    """
    root = Path(root)
    items = build_gold_set(per_class, seed)
    result = score_gold_set(items, score_bin_path(root))

    out_dir = root / "research" / "nyaya" / "validity"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"night-{night}-{condition.replace(':', '-')}-constructed.json"
    out_path.write_text(json.dumps(result, indent=1, sort_keys=True) + "\n")
    sha256 = hashlib.sha256(out_path.read_bytes()).hexdigest()

    payload = {
        "kind": "external_eval",
        "severity": "info",
        "tier": TIER_KERNEL,
        "track": TRACK,
        "condition": condition,
        "model": "pravrudhi-kernel+prabhasa-nyaya-lean",
        "file": str(out_path.relative_to(root)),
        "sha256": sha256,
        "tool": TOOL_NYAYA_VALIDITY,
        "n_samples": {"nyaya_validity": result["n"]},
        "metrics": {"nyaya_validity": {"pass_rate": result["pass_rate"]}},
        "per_class": result["per_class"],
        "decided_classes": result["decided_classes"],
        "not_decided_classes": result["not_decided_classes"],
        "lean_source_commit": result["lean_source_commit"],
    }
    ledger = root / "research" / "ledger.jsonl"
    w = LedgerWriter.open(ledger, "0.1.0")
    ev = w.append("audit", "auditor", payload, epoch=0, night=night)
    return {"seq": ev.seq, **payload}
