"""Model loading, batched greedy generation, and NLL scoring for the 1.13B
Megatron-Core NemotronH checkpoint, exposing the same
`load_model / generate / sequence_nll / linear_module_names` contract as
`model_io.py` (the 370M line's adapter) so `evaluate.py` can switch between
the two model families by a flag instead of a rewrite.

Wraps Track B's own loader (`scripts/m4/eval_adapter.py::load_megatron_blob`
+ `_init_distributed_for_eval`) rather than reimplementing checkpoint
reconstruction -- same principle `model_io.py` states for the 370M line
("single source of truth"). `ByteTokenizer` is the same class `model_io.py`
loads by path (`/trackB/src/prabhasa/application/tokenizer/bytelevel.py`);
imported here the identical way so both adapters agree on encode/decode.

Padding/generation invariant: identical to `model_io.py` and
`scripts/m7/generate.py`. `StructuredNemotronH.forward` always calls
Megatron's `MambaModel` with `attention_mask=None`; Mamba2's recurrence has
no masking path, so padding a prompt with a real byte value (even 0) ahead of
content the model still has to predict would inject fake context into that
row's own hidden state and corrupt every subsequent generated byte for it.
Batches are therefore grouped by EXACT prompt length and never padded here,
exactly like `model_io.py::generate` / `scripts/m7/generate.py::
group_by_length` + `batched_greedy_decode`. (This is a different situation
from `train_megatron_sft.py`'s fixed-length padding for *training*, which is
safe because trailing pad bytes there only ever affect that row's own
-100-masked loss positions, never another row's state or a still-to-be-
predicted position -- see `collate.py`'s docstring for the full argument.)

LoRA note: `linear_module_names` below is kept for interface parity with
`model_io.py`, but on this model it will typically return an EMPTY list --
Megatron's `ColumnParallelLinear`/`RowParallelLinear`/transformer-engine
`Linear` layers are not `torch.nn.Linear` subclasses (see
`lora_megatron.py`'s docstring for the full reasoning). Use
`lora_megatron.find_lora_targets` / `inject_lora_generic` for this model
instead of `ttt.py::inject_lora`; `linear_module_names` is not deleted here
only so a caller iterating both adapters by the same attribute name gets an
honest (empty-or-near-empty) answer rather than an AttributeError.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any

TRACKB_ROOT = Path("/trackB")
_EVAL_ADAPTER_DIR = TRACKB_ROOT / "scripts" / "m4"
_BYTETOKENIZER_MODULE = (
    TRACKB_ROOT / "src" / "prabhasa" / "application" / "tokenizer" / "bytelevel.py"
)


def _load_module_from_path(name: str, path: Path) -> Any:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load module {name!r} from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _eval_adapter_module() -> Any:
    """`eval_adapter.py` uses a relative `sys.path`-based import style
    internally (none, actually -- it's self-contained) but does live inside
    `scripts/m4`, which itself expects to be on `sys.path` for any sibling
    imports it might grow later; add the dir, not just the file, to match how
    `train_megatron_sft.py` and the original dry-run script both load it."""
    if str(_EVAL_ADAPTER_DIR) not in sys.path:
        sys.path.insert(0, str(_EVAL_ADAPTER_DIR))
    return _load_module_from_path("prabhasa_eval_adapter", _EVAL_ADAPTER_DIR / "eval_adapter.py")


def _byte_tokenizer_class() -> Any:
    return _load_module_from_path("prabhasa_bytelevel", _BYTETOKENIZER_MODULE).ByteTokenizer


def checkpoint_sha256_prefix(ckpt_path: str | Path, n_bytes: int = 1 << 20) -> str:
    import hashlib

    h = hashlib.sha256()
    with open(ckpt_path, "rb") as f:
        h.update(f.read(n_bytes))
    return h.hexdigest()


def load_model(
    ckpt_path: str | Path, device: str = "cuda:0", config_path: str | Path | None = None
) -> tuple[Any, Any]:
    """Load the Megatron-Core `StructuredNemotronH` model + a `ByteTokenizer`
    from an M4-format checkpoint blob (`{step, tokens_seen, cursor, model,
    opt, arm, override_pattern}`) via `eval_adapter.load_megatron_blob`.

    Unlike `model_io.py::load_model`'s direct `torch.load`, this delegates
    the whole load (including the `mmap=True` + drop-`opt` RAM discipline,
    and `_init_distributed_for_eval`'s process-group setup MambaModel
    requires even on a single GPU) to `eval_adapter.py`, since that is the
    only correct way to reconstruct this architecture -- there is no
    standalone module class to import the way `model_io.py` imports
    `NemotronH` from `train_130m.py`.
    """
    ea = _eval_adapter_module()
    model, cfg = ea.load_megatron_blob(Path(ckpt_path), config_path=config_path, device=device)
    tok = _byte_tokenizer_class()()
    return model, tok


def _batched_greedy_decode(
    model: Any, prompt_ids_batch: list[list[int]], max_new_tokens: int, device: Any
) -> list[list[int]]:
    """All prompts must already be the same length -- see module docstring
    for why padding is not an option here."""
    import torch

    lengths = {len(p) for p in prompt_ids_batch}
    if len(lengths) > 1:
        raise ValueError(f"_batched_greedy_decode requires equal-length prompts, got {lengths}")
    ids = torch.tensor(prompt_ids_batch, dtype=torch.long, device=device)
    generated: list[list[int]] = [[] for _ in prompt_ids_batch]
    with torch.no_grad():
        for _ in range(max_new_tokens):
            zeros = torch.zeros_like(ids)
            with torch.autocast(
                ids.device.type, dtype=torch.bfloat16, enabled=(ids.device.type == "cuda")
            ):
                logits = model(ids, zeros, zeros)
            next_ids = logits[:, -1].argmax(dim=-1)
            ids = torch.cat([ids, next_ids.unsqueeze(1)], dim=1)
            for b in range(len(prompt_ids_batch)):
                generated[b].append(int(next_ids[b]))
    return generated


def generate(
    model: Any,
    tok: Any,
    prompts: list[str],
    max_new_tokens: int = 256,
    stop: list[str] | None = None,
    max_batch_size: int = 16,
) -> list[str]:
    """Greedy byte-level generation, batched by exact prompt length, never
    padded. `stop` truncates the decoded text post-hoc at the earliest match
    (the byte vocab has no EOS, so `max_new_tokens` bytes are always
    generated; `stop` only affects what is returned) -- identical semantics
    to `model_io.py::generate`."""
    device = next(model.parameters()).device
    prompt_ids_list = [tok.encode(p) for p in prompts]

    groups: dict[int, list[int]] = {}
    for i, ids in enumerate(prompt_ids_list):
        groups.setdefault(len(ids), []).append(i)

    out_ids: dict[int, list[int]] = {}
    for _length, indices in groups.items():
        for start in range(0, len(indices), max_batch_size):
            chunk = indices[start : start + max_batch_size]
            chunk_prompts = [prompt_ids_list[i] for i in chunk]
            decoded = _batched_greedy_decode(model, chunk_prompts, max_new_tokens, device)
            for i, ids in zip(chunk, decoded, strict=True):
                out_ids[i] = ids

    texts = [tok.decode(out_ids[i]) for i in range(len(prompts))]
    if stop:
        truncated = []
        for text in texts:
            cut = len(text)
            for s in stop:
                idx = text.find(s)
                if idx != -1:
                    cut = min(cut, idx)
            truncated.append(text[:cut])
        texts = truncated
    return texts


def sequence_nll(model: Any, tok: Any, prompt: str, continuation: str) -> float:
    """Mean NLL (nats) over continuation bytes only -- identical semantics
    and identical caveats to `model_io.py::sequence_nll` (empty-prompt
    first-byte exclusion; no `torch.no_grad()`, since `ttt.py::adapt` needs
    gradients to flow into injected LoRA params during TTT)."""
    import torch

    device = next(model.parameters()).device
    prompt_ids = tok.encode(prompt)
    cont_ids = tok.encode(continuation)
    all_ids = prompt_ids + cont_ids
    if len(all_ids) < 2:
        return 0.0

    n_prompt = len(prompt_ids)
    tokens = torch.tensor([all_ids], dtype=torch.long, device=device)
    zeros = torch.zeros_like(tokens)
    with torch.autocast(device.type, dtype=torch.bfloat16, enabled=(device.type == "cuda")):
        logits = model(tokens, zeros, zeros)[0]

    targets = tokens[0, 1:]
    preds = logits[:-1]

    j_start = max(n_prompt - 1, 0)
    if j_start >= targets.shape[0]:
        return 0.0

    sel_preds = preds[j_start:].float()
    sel_targets = targets[j_start:]
    nll = torch.nn.functional.cross_entropy(sel_preds, sel_targets, reduction="mean")
    return float(nll.item())


def linear_module_names(model: Any) -> list[str]:
    """`nn.Linear` submodules only -- kept for interface parity with
    `model_io.py`; almost certainly empty on this model (see module
    docstring). Use `lora_megatron.find_lora_targets` for actual LoRA
    targeting on the Megatron model."""
    import torch.nn as nn

    return [name for name, module in model.named_modules() if isinstance(module, nn.Linear)]


def model_config(model: Any) -> dict[str, Any]:
    """Best-effort config recovery matching `model_io.py::model_config`'s
    contract, using the fields `StructuredNemotronH` actually stores on
    `self` (unlike the 370M `NemotronH`, this wrapper does keep `vocab_size`
    and the derived hybrid `pattern` -- no shape-reconstruction needed for
    those two)."""
    return {
        "vocab_size": model.vocab_size,
        "override_pattern": model.pattern,
        "structured": model.structured,
    }
