"""Model loading, batched greedy generation, and NLL scoring for the 1.13B
Megatron-Core NemotronH checkpoint, exposing the same
`load_model / generate / sequence_nll / linear_module_names` contract as
`model_io.py` (the 370M line's adapter) so `evaluate.py` can switch between
the two model families by a flag instead of a rewrite.

Wraps Track B's own loader (`scripts/m4/eval_adapter.py::load_megatron_blob`
+ `_init_distributed_for_eval`) rather than reimplementing checkpoint
reconstruction -- same principle `model_io.py` states for the 370M line
("single source of truth"). `ByteTokenizer` is the same class `model_io.py`
loads by path (`/trackB/src/prabhasa/application/tokenizer/bytelevel.py`);
imported here the identical way so both adapters agree on encode/decode.

Padding/generation invariant: identical to `model_io.py` and
`scripts/m7/generate.py`. `StructuredNemotronH.forward` always calls
Megatron's `MambaModel` with `attention_mask=None`; Mamba2's recurrence has
no masking path, so padding a prompt with a real byte value (even 0) ahead of
content the model still has to predict would inject fake context into that
row's own hidden state and corrupt every subsequent generated byte for it.
Batches are therefore grouped by EXACT prompt length and never padded here,
exactly like `model_io.py::generate` / `scripts/m7/generate.py::
group_by_length` + `batched_greedy_decode`. (This is a different situation
from `train_megatron_sft.py`'s fixed-length padding for *training*, which is
safe because trailing pad bytes there only ever affect that row's own
-100-masked loss positions, never another row's state or a still-to-be-
predicted position -- see `collate.py`'s docstring for the full argument.)

LoRA note: `linear_module_names` below is kept for interface parity with
`model_io.py`, but on this model it will typically return an EMPTY list --
Megatron's `ColumnParallelLinear`/`RowParallelLinear`/transformer-engine
`Linear` layers are not `torch.nn.Linear` subclasses (see
`lora_megatron.py`'s docstring for the full reasoning). Use
`lora_megatron.find_lora_targets` / `inject_lora_generic` for this model
instead of `ttt.py::inject_lora`; `linear_module_names` is not deleted here
only so a caller iterating both adapters by the same attribute name gets an
honest (empty-or-near-empty) answer rather than an AttributeError.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any

TRACKB_ROOT = Path("/trackB")
_EVAL_ADAPTER_DIR = TRACKB_ROOT / "scripts" / "m4"
_BYTETOKENIZER_MODULE = (
    TRACKB_ROOT / "src" / "prabhasa" / "application" / "tokenizer" / "bytelevel.py"
)


def _load_module_from_path(name: str, path: Path) -> Any:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load module {name!r} from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _eval_adapter_module() -> Any:
    """`eval_adapter.py` uses a relative `sys.path`-based import style
    internally (none, actually -- it's self-contained) but does live inside
    `scripts/m4`, which itself expects to be on `sys.path` for any sibling
    imports it might grow later; add the dir, not just the file, to match how
    `train_megatron_sft.py` and the original dry-run script both load it."""
    if str(_EVAL_ADAPTER_DIR) not in sys.path:
        sys.path.insert(0, str(_EVAL_ADAPTER_DIR))
    return _load_module_from_path("prabhasa_eval_adapter", _EVAL_ADAPTER_DIR / "eval_adapter.py")


def _byte_tokenizer_class() -> Any:
    return _load_module_from_path("prabhasa_bytelevel", _BYTETOKENIZER_MODULE).ByteTokenizer


def checkpoint_sha256_prefix(ckpt_path: str | Path, n_bytes: int = 1 << 20) -> str:
    import hashlib

    h = hashlib.sha256()
    with open(ckpt_path, "rb") as f:
        h.update(f.read(n_bytes))
    return h.hexdigest()


def load_model(
    ckpt_path: str | Path, device: str = "cuda:0", config_path: str | Path | None = None
) -> tuple[Any, Any]:
    """Load the Megatron-Core `StructuredNemotronH` model + a `ByteTokenizer`
    from an M4-format checkpoint blob (`{step, tokens_seen, cursor, model,
    opt, arm, override_pattern}`) via `eval_adapter.load_megatron_blob`.

    Unlike `model_io.py::load_model`'s direct `torch.load`, this delegates
    the whole load (including the `mmap=True` + drop-`opt` RAM discipline,
    and `_init_distributed_for_eval`'s process-group setup MambaModel
    requires even on a single GPU) to `eval_adapter.py`, since that is the
    only correct way to reconstruct this architecture -- there is no
    standalone module class to import the way `model_io.py` imports
    `NemotronH` from `train_130m.py`.
    """
    ea = _eval_adapter_module()
    model, cfg = ea.load_megatron_blob(Path(ckpt_path), config_path=config_path, device=device)
    tok = _byte_tokenizer_class()()
    return model, tok


def _model_io_module() -> Any:
    """Import `model_io.py` the same "works with or without a package import
    context" way this file already imports `eval_adapter.py` / `bytelevel.py`
    (`_load_module_from_path`), rather than a bare `from .. import model_io`
    -- this file has historically also been imported standalone via a
    `sys.path` insertion (see `runs/g0_sft_round1/_smoke_driver.py`), where a
    relative import would raise "attempted relative import with no known
    parent package". Try the normal package import first (cheap, and shares
    the already-loaded module when this file *is* imported as part of
    `prototypes.nyaya_ttt_rsi.g0`); fall back to a path-based load otherwise.
    """
    try:
        from .. import model_io as mio

        return mio
    except ImportError:
        return _load_module_from_path(
            "prabhasa_nyaya_model_io", Path(__file__).resolve().parent.parent / "model_io.py"
        )


# `generate` / `sequence_nll`: delegate to `model_io.py` rather than keeping
# byte-identical copies here. Both model families expose the exact same
# `forward(tokens, boundary, roles) -> logits` signature (see this module's
# docstring), so `model_io.py`'s batched-greedy-decode / NLL implementation
# already works unchanged for the Megatron model -- there is exactly one
# implementation of this logic in the codebase now, not two copies that
# could silently drift apart.


def generate(
    model: Any,
    tok: Any,
    prompts: list[str],
    max_new_tokens: int = 256,
    stop: list[str] | None = None,
    max_batch_size: int = 16,
) -> list[str]:
    """See `model_io.py::generate` -- identical semantics, delegated."""
    return _model_io_module().generate(
        model, tok, prompts, max_new_tokens=max_new_tokens, stop=stop, max_batch_size=max_batch_size
    )


def sequence_nll(model: Any, tok: Any, prompt: str, continuation: str) -> float:
    """See `model_io.py::sequence_nll` -- identical semantics, delegated."""
    return _model_io_module().sequence_nll(model, tok, prompt, continuation)


def linear_module_names(model: Any) -> list[str]:
    """`nn.Linear` submodules only -- kept for interface parity with
    `model_io.py`; almost certainly empty on this model (see module
    docstring). Use `lora_megatron.find_lora_targets` for actual LoRA
    targeting on the Megatron model."""
    import torch.nn as nn

    return [name for name, module in model.named_modules() if isinstance(module, nn.Linear)]


def model_config(model: Any) -> dict[str, Any]:
    """Best-effort config recovery matching `model_io.py::model_config`'s
    contract, using the fields `StructuredNemotronH` actually stores on
    `self` (unlike the 370M `NemotronH`, this wrapper does keep `vocab_size`
    and the derived hybrid `pattern` -- no shape-reconstruction needed for
    those two)."""
    return {
        "vocab_size": model.vocab_size,
        "override_pattern": model.pattern,
        "structured": model.structured,
    }
